src/main/java/com/mycompany/mavenproject/controller/FormularioController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.mavenproject.controller;

import com.mycompany.mavenproject.Dto.PersonaDto;
import com.mycompany.mavenproject.Dto.TipoDocumetoDto;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import org.primefaces.PrimeFaces;


/**
 *
 * @author SUBOCOL
 */
@Named(value = "formularioController")
@ViewScoped
public class FormularioController implements Serializable{

    PersonaDto personaDto=new PersonaDto();
    int id=0;
    List<TipoDocumetoDto> documeto;
    List<PersonaDto> personaDtos = new ArrayList<>();
    
    @PostConstruct
    public void init() {
        documeto = new ArrayList<>();

        documeto.add(new TipoDocumetoDto(1,"Cedula"));
        documeto.add(new TipoDocumetoDto(2,"Tarjeta identidad"));

    }
    
    public FormularioController() {
    }

    public void crearPersona(){
        
        personaDtos.add(new PersonaDto(personaDtos.size()+1, personaDto.getNombre(), personaDto.getApellido(), 
                personaDto.getNumeroDocumento(), personaDto.getFechaNacimento(), documeto.get(id-1)));
        
    }

    public void deletePersona() {
        this.personaDtos.remove(this.personaDto);
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Product Removed"));
        PrimeFaces.current().ajax().update("form:messages", "form:dt-products");
    }
    
    public void savePersona() {
        if (this.personaDto.getId() == 0) {
            this.personaDto.setId(personaDtos.size()+1);
            this.personaDtos.add(this.personaDto);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Product Added"));
        }
        else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Product Updated"));
        }

        PrimeFaces.current().executeScript("PF('manageProductDialog').hide()");
        PrimeFaces.current().ajax().update("form:messages", "form:dt-products");
    }

    public List<PersonaDto> getPersonaDtos() {
        return personaDtos;
    }

    public void setPersonaDtos(List<PersonaDto> personaDtos) {
        this.personaDtos = personaDtos;
    }
    
    public PersonaDto getPersonaDto() {
        return personaDto;
    }

    public void setPersonaDto(PersonaDto personaDto) {
        this.personaDto = personaDto;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void TipoDocumentoController() {
    }
 
    public List<TipoDocumetoDto> getDocumetoDto() {
        return documeto;
    }

    public void setDocumetoDto(List<TipoDocumetoDto> documeto) {
        this.documeto = documeto;
    }
    
    
    
}

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>

        <title>Formulario Persona</title>
    </h:head>
    <h:body>
        <div class="card crud-demo">
            <h:form id="form">
                <h1 >Persona</h1>
                <p:growl id="messages" showDetail="true" />

                <h:panelGrid id="panel" columns="6">
                    <p:outputLabel for="nombre" value="Nombre"/>
                    <p:inputText id="nombre" value="#{formularioController.personaDto.nombre}" required="true" label="Nombre">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="nombre"/>
                    <p:outputLabel for="apellido" value="Apellido"/>
                    <p:inputText id="apellido" value="#{formularioController.personaDto.apellido}" required="true" label="Apellido">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="apellido"/>
                    <p:outputLabel for="@next" value="Tipo Documento"/>
                    <p:selectOneMenu id="tipoDoc" value="#{formularioController.id}">
                        <f:selectItem itemLabel="Selecionar" itemValue=""/>
                        <f:selectItems value="#{formularioController.documetoDto}" var="c" itemValue="#{c.id}" itemLabel="#{c.nombre}"/>
                    </p:selectOneMenu>
                    <p:message for="tipoDoc"/>
                    <p:outputLabel for="documento" value="Documento"/>
                    <p:inputText id="documento" value="#{formularioController.personaDto.numeroDocumento}" required="true" label="Documento">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="documento"/>
                    <p:outputLabel for="fecha" value="Fecha Nacimiento"/>
                    <p:datePicker id="fecha" value="#{formularioController.personaDto.fechaNacimento}" />
                    <p:message for="fecha"/>
                </h:panelGrid>

                <p:commandButton id="submitButton" value="Save" update="@parent" action="#{formularioController.crearPersona()}" styleClass="mt-3" />

                <p:dataTable id="dt-products" widgetVar="dtProducts" var="p" value="#{formularioController.personaDtos}"
                             reflow="true" styleClass="products-table" selection=""
                             rowKey="#{p.id}" paginator="true" rows="10" rowSelectMode="add" 
                             paginatorPosition="bottom">

                    <p:column headerText="Nombre">
                        <h:outputText value="#{p.nombre}" />
                    </p:column>

                    <p:column headerText="Apellido">
                        <h:outputText value="#{p.apellido}" />
                    </p:column>

                    <p:column headerText="Tipo Docuemto">
                        <h:outputText value="#{p.tipoDocumento.nombre}" />
                    </p:column>

                    <p:column headerText="Nro. Documento">
                        <h:outputText value="#{p.numeroDocumento}" />
                    </p:column>
                    <p:column headerText="Fecha Nacimiento">
                        <h:outputText value="#{p.fechaNacimento}" />
                    </p:column>
                    <p:column exportable="false">
                        <p:commandButton icon="pi pi-pencil" update=":dialogs:manage-product-content"
                    oncomplete="PF('manageProductDialog').show()"
                    styleClass="edit-button rounded-button ui-button-success" process="@this">
                    <f:setPropertyActionListener value="#{p}" target="#{formularioController.personaDto}" />
                    <p:resetInput target=":dialogs:manage-product-content" />
                </p:commandButton>
                        <p:commandButton class="ui-button-warning rounded-button" icon="pi pi-trash" process="@this"
                                         oncomplete="PF('deleteProductDialog').show()">
                            <f:setPropertyActionListener value="#{p}" target="#{formularioController.personaDto}" />
                        </p:commandButton>
                    </p:column>
                </p:dataTable>


            </h:form>   

            <h:form id="dialogs">
                <p:dialog header="Detalle Persona" showEffect="fade" modal="true" widgetVar="manageProductDialog"
                          responsive="true">
                    <p:outputPanel id="manage-product-content" class="ui-fluid">
                        <p:outputPanel rendered="#{not empty formularioController.personaDto}">
                    <p:outputLabel for="nombre" value="Nombre"/>
                    <p:inputText id="nombre" value="#{formularioController.personaDto.nombre}" required="true" label="Nombre">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="nombre"/>
                    <p:outputLabel for="apellido" value="Apellido"/>
                    <p:inputText id="apellido" value="#{formularioController.personaDto.apellido}" required="true" label="Apellido">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="apellido"/>
                    <p:outputLabel for="@next" value="Tipo Documento"/>
                    <p:selectOneMenu id="tipoDoc" value="#{formularioController.id}">
                        <f:selectItem itemLabel="Selecionar" itemValue=""/>
                        <f:selectItems value="#{formularioController.documetoDto}" var="d" itemValue="#{d.id}" itemLabel="#{d.nombre}"/>
                    </p:selectOneMenu>
                    <p:message for="tipoDoc"/>
                    <p:outputLabel for="documento" value="Documento"/>
                    <p:inputText id="documento" value="#{formularioController.personaDto.numeroDocumento}" required="true" label="Documento">
                        <f:validateLength minimum="2"/>
                    </p:inputText>
                    <p:message for="documento"/>
                    <p:outputLabel for="fecha" value="Fecha Nacimiento"/>
                    <p:datePicker id="fecha" value="#{formularioController.personaDto.fechaNacimento}" />
                    <p:message for="fecha"/>
                     </p:outputPanel>                  
                    </p:outputPanel>

                   <f:facet name="footer">
                       <p:commandButton value="Guardar" icon="pi pi-check" actionListener="#{formularioController.savePersona()}"
                    update="manage-product-content" process="manage-product-content @this" />
                <p:commandButton value="Cancel" icon="pi pi-times" onclick="PF('manageProductDialog').hide()"
                    class="ui-button-secondary" type="button" />
            </f:facet>
                </p:dialog>

                <p:confirmDialog widgetVar="deleteProductDialog" showEffect="fade" width="300"
                                 message="Eliminar Persona?" header="Confirm" severity="warn">
                    <p:commandButton value="Yes" icon="pi pi-check" actionListener="#{formularioController.deletePersona()}"
                                     process="@this" oncomplete="PF('deleteProductDialog').hide()" />
                    <p:commandButton value="No" type="button" styleClass="ui-button-secondary" icon="pi pi-times"
                                     onclick="PF('deleteProductDialog').hide()" />
                </p:confirmDialog>

                <p:confirmDialog global="true" showEffect="fade" width="300">
                    <p:commandButton value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no ui-button-secondary"
                                     icon="pi pi-times" />
                </p:confirmDialog>
            </h:form>


        </div>
    </h:body>
</html>